/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nlp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[7] = {2, 2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s3[7] = {1, 2, 0, 1, 2, 0, 0};

/* nlp:(x[2],p)->(f,g) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = sq(@0) */
  w1 = casadi_sq( w0 );
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1+@3) */
  w1 += w3;
  /* #5: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #6: @0 = (@0+@2) */
  w0 += w2;
  /* #7: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #8: @0 = (@0-@2) */
  w0 -= w2;
  /* #9: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_out(casadi_int i) {
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* nlp_f:(x[2],p)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #2: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #3: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #4: @0 = (@0+@1) */
  w0 += w1;
  /* #5: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_f_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_out(casadi_int i) {
  switch (i) {
    case 0: return "f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* nlp_g:(x[2],p)->(g) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @0 = (@0+@1) */
  w0 += w1;
  /* #3: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #4: @0 = (@0-@1) */
  w0 -= w1;
  /* #5: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_g_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* nlp_grad:(x[2],p,lam_f,lam_g)->(f,g,grad_gamma_x[2],grad_gamma_p) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = sq(@0) */
  w1 = casadi_sq( w0 );
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1+@3) */
  w1 += w3;
  /* #5: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #6: @1 = (@0+@2) */
  w1  = (w0+w2);
  /* #7: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #8: @1 = (@1-@3) */
  w1 -= w3;
  /* #9: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  /* #10: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #11: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #12: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #13: @0 = (@0*@3) */
  w0 *= w3;
  /* #14: @0 = (@1+@0) */
  w0  = (w1+w0);
  /* #15: output[2][0] = @0 */
  if (res[2]) res[2][0] = w0;
  /* #16: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #17: @2 = (@2*@3) */
  w2 *= w3;
  /* #18: @2 = (@1+@2) */
  w2  = (w1+w2);
  /* #19: output[2][1] = @2 */
  if (res[2]) res[2][1] = w2;
  /* #20: @1 = (-@1) */
  w1 = (- w1 );
  /* #21: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_grad_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_grad_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real nlp_grad_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_out(casadi_int i) {
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    case 2: return "grad_gamma_x";
    case 3: return "grad_gamma_p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* nlp_grad_f:(x[2],p)->(f,grad_f_x[2]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = sq(@0) */
  w1 = casadi_sq( w0 );
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1+@3) */
  w1 += w3;
  /* #5: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #6: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #7: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #8: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #9: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_grad_f_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_out(casadi_int i) {
  switch (i) {
    case 0: return "f";
    case 1: return "grad_f_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* nlp_hess_l:(x[2],p,lam_f,lam_g)->(triu_hess_gamma_x_x[2x2,2nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+3, w3, w4;
  /* #0: @0 = zeros(2x2,2nz) */
  casadi_clear(w0, 2);
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = ones(2x1) */
  casadi_fill(w2, 2, 1.);
  /* #3: {@3, @4} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  /* #4: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #5: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #6: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #7: @1 = (@1*@4) */
  w1 *= w4;
  /* #8: @2 = vertcat(@3, @1) */
  rr=w2;
  *rr++ = w3;
  *rr++ = w1;
  /* #9: (@0[:2] = @2) */
  for (rr=w0+0, ss=w2; rr!=w0+2; rr+=1) *rr = *ss++;
  /* #10: (@0[:2] = @2) */
  for (rr=w0+0, ss=w2; rr!=w0+2; rr+=1) *rr = *ss++;
  /* #11: @2 = @0' */
  casadi_trans(w0,casadi_s2, w2, casadi_s2, iw);
  /* #12: output[0][0] = @2 */
  casadi_copy(w2, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_hess_l_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_out(casadi_int i) {
  switch (i) {
    case 0: return "triu_hess_gamma_x_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 7;
  return 0;
}

/* nlp_jac_g:(x[2],p)->(g,jac_g_x[1x2]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, *w2=w+2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @0 = (@0+@1) */
  w0 += w1;
  /* #3: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #4: @0 = (@0-@1) */
  w0 -= w1;
  /* #5: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #6: @2 = zeros(2x1) */
  casadi_clear(w2, 2);
  /* #7: @0 = ones(2x1,1nz) */
  w0 = 1.;
  /* #8: {@1, NULL} = vertsplit(@0) */
  w1 = w0;
  /* #9: (@2[0] = @1) */
  for (rr=w2+0, ss=(&w1); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #10: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #11: {NULL, @0} = vertsplit(@1) */
  w0 = w1;
  /* #12: (@2[1] = @0) */
  for (rr=w2+1, ss=(&w0); rr!=w2+2; rr+=1) *rr = *ss++;
  /* #13: output[1][0] = @2 */
  casadi_copy(w2, 2, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_jac_g_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    case 1: return "jac_g_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
