import os
import datetime
from controller.settings import *


SETTINGS = {}
SETTINGS['WORKSPACE'] = WORKSPACE_SETTINGS
SETTINGS['FIGURES'] = FIG_LIST
SETTINGS['PLOTS'] = PLOT_SETTINGS
SETTINGS['SIMS'] = SIMS_SETTINGS
SETTINGS['VIDEO'] = VIDEO
SETTINGS['INIT_CONDS'] = INIT_CONDS

SETTINGS['verbose'] = True
SETTINGS['save_log'] = False
SETTINGS['save_path'] = ''
